
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}

      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: docker info && gcloud auth configure-docker

    - name: Build Docker
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/vreshch-com:latest .

    - name: Push Docker image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/vreshch-com:latest

    - name: Update Infrastructure
      run: terraform init && terraform plan && terraform apply -auto-approve -lock=false

